# Generated by Django 4.1.7 on 2023-03-25 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentscore',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='phonecall',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='tc',
            name='tc_group',
        ),
        migrations.RemoveField(
            model_name='tc',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tcphonecall',
            name='tc',
        ),
        migrations.RemoveField(
            model_name='tcphonecallscore',
            name='tc',
        ),
        migrations.RemoveField(
            model_name='tcscore',
            name='tc',
        ),
        migrations.RemoveField(
            model_name='td',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tdscore',
            name='td',
        ),
        migrations.RemoveField(
            model_name='tm',
            name='td',
        ),
        migrations.RemoveField(
            model_name='tmscore',
            name='tm',
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='AgentScore',
        ),
        migrations.DeleteModel(
            name='PhoneCall',
        ),
        migrations.DeleteModel(
            name='TC',
        ),
        migrations.DeleteModel(
            name='TCGroup',
        ),
        migrations.DeleteModel(
            name='TCPhoneCall',
        ),
        migrations.DeleteModel(
            name='TCPhoneCallScore',
        ),
        migrations.DeleteModel(
            name='TCScore',
        ),
        migrations.DeleteModel(
            name='TD',
        ),
        migrations.DeleteModel(
            name='TDScore',
        ),
        migrations.DeleteModel(
            name='TM',
        ),
        migrations.DeleteModel(
            name='TMScore',
        ),
    ]
