# Generated by Django 4.1.7 on 2023-03-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_agent_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonecall',
            name='date',
        ),
    ]
