# Generated by Django 4.1.7 on 2023-03-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_phonecall_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecall',
            name='score',
            field=models.FloatField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
